on: [push]
jobs:
  Post-Push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: rubocop

      - name: Run Reek
        run: reek

      - name: Run tests
        run: rspec
    